site_name: "neuralfields"
site_author: "Fabio Muratore"
site_description: "A type of potential-based recurrent neural networks implemented with PyTorch"
site_dir: .site
site_url: "https://famura.github.io/neuralfields"
repo_name: "famura/neuralfields"
repo_url: "https://github.com/famura/neuralfields"
edit_uri: "blob/main/docs"

nav:
  - Overview:
    - Overview: index.md
    - Getting Started: getting_started.md
    - Changelog: exported/changelog.md
  - Code Reference: reference/
  - Development:
    - Contributing: contributing.md
    - Coverage: exported/coverage/report.html
    - Tests: exported/tests/report.html
  - License:
    - This Project: license.md
    - Third-Party Libraries: exported/third_party_licenses.md

theme:
  name: material
  features:
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
#  font: false # Disabled because of GDPR, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#autoloading
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      accent: indigo
      media: "(prefers-color-scheme: light)"
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      accent: deep orange
      media: "(prefers-color-scheme: dark)"
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - gen-files:
      scripts:
        - docs/generate_code_reference.py
  - git-revision-date-localized:
      fallback_to_build_date: true
  - literate-nav:
      nav_file: code_nav.md
  - minify:
      minify_html: true
  - mkdocstrings:
      # https://mkdocstrings.github.io/usage/#cross-references-to-other-projects-inventories
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
          options:
            show_source: true
            inherited_members: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
  - search

extra:
  generator: false
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  # Sortable tables (see https://squidfunk.github.io/mkdocs-material/reference/data-tables)
  - https://unpkg.com/tablesort/dist/tablesort.min.js
  - js/tablesort.js

  # MathJax (see https://squidfunk.github.io/mkdocs-material/reference/mathjax)
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
